# Generated by Django 2.2.6 on 2019-10-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191018_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
